project: 
  type: website
  
website: 
  page-navigation: true
  title: "OHI+" 
  site-url: "https://ohi-rsga.github.io/OHI_RSGA/" 
  repo-url: https://github.com/ohi-rsga/OHI_RSGA 
  repo-actions: [edit, issue]
  
  page-footer:
    right: "Something here?"
    left: "An Ocean Health Index collaboration"
    
  sidebar:
    logo: "chapters/figs/redsea_globalmap.png"
    pinned: true
    align: center
    style: "docked"
    search: true
    collapse-level: 1
    contents:
      - href: index.qmd
        text: Welcome
      - href: chapters/OHI.qmd
        text: "Overview of OHI"
      - href: chapters/region.qmd
        text: "Region"
      - section: "Goals"
        contents:
          - href: chapters/ao.qmd
            text: "Artisanal opportunities"
          - href: chapters/bd.qmd
            text: "Biodiversity"
          - href: chapters/cs.qmd
            text: "Carbon storage"
          - href: chapters/cw.qmd
            text: "Clean waters"
          - href: chapters/cp.qmd
            text: "Coastal protection"
          - href: chapters/fp.qmd
            text: "Food provision"
          - href: chapters/le.qmd
            text: "Livelihoods and economies"
          - href: chapters/np.qmd
            text: "Natural products"
          - href: chapters/sp.qmd
            text: "Sense of place"
          - href: chapters/tr.qmd
            text: "Tourism and recreation"
      - href: chapters/pressures.qmd
        text: "Pressures"
      - href: chapters/resilience.qmd
        text: "Resilience"
format:
  html:
    theme:
      light: [cosmo, theme.scss] # from https://github.com/sta210-s22/website/blob/main/_quarto.yml
      dark: [cosmo, theme-dark.scss]
    code-copy: true
    code-overflow: wrap
    toc: true
    
filters:
  - quarto


