project:
  type: website

website:
  title: "OHI_RSGA"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
  sidebar:
    style: "docked"
    search: true
    contents:
      - section: "Food Provisioning"
        contents:
          - chapters/dog.qmd
          - chapters/cat.qmd
      - section: "Artisanal Opportunities"
        contents:
          - chapters/horse.qmd
          
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



