---
title: "OHI_data"
output: html_document
date: "2023-11-22"
---

```{r setup, include=FALSE}
library(sf)
library(terra)
library(tidyverse)
library(here)
library(countrycode)
library(tidyr)

```

## Get spatial data
Created using scripts in the _spatial folder.
```{r}

regions <- st_read(here("_spatial/data/eez.shp"))
```

## Get OHI data
```{r}

ohi <- read_csv("https://raw.githubusercontent.com/OHI-Science/ohi-global/draft/yearly_results/global2023/OHI_final_formatted_scores_2023-10-02.csv")

#write_csv(ohi, here("data/output/original_ohi.csv"))

ohi$iso3c <- countrycode(ohi$region_name, "country.name", "iso3c")

ohi <- ohi %>%
  filter(scenario == 2023) %>%
  filter(dimension == "score") %>%
  filter(!is.na(iso3c)) %>%
  select(iso3c, region_name, goal, value) %>%
  pivot_wider(names_from = goal, values_from = value)

```

## Combine
```{r}
scores <- left_join(regions, ohi, by="iso3c") %>%
  filter(iso3c != "SDN/EGY") %>% #disputed areas
  filter(iso3c != "ERI/DJI")

#st_write(scores, here("data/output/scores.shp"))


```


## Data with all score components
```{r}
ohi <- read_csv("https://raw.githubusercontent.com/OHI-Science/ohi-global/draft/yearly_results/global2023/OHI_final_formatted_scores_2023-10-02.csv")

ohi$iso3c <- countrycode(ohi$region_name, "country.name", "iso3c")

ohi <- ohi %>%
  filter(scenario == 2023) %>%
  filter(!is.na(iso3c)) %>%
  filter(iso3c %in% regions$iso3c) %>%
  select(iso3c, region_name, goal, dimension, value) %>%
  pivot_wider(names_from = dimension, values_from = value)

areas <- st_drop_geometry(select(regions, c(iso3c, are_km2))) %>%
  filter(!(iso3c %in% c("SDN/EGY", "ERI/DJI"))) %>%
  group_by(iso3c) %>%
  summarize(are_km2 = sum(are_km2))

ohi <- left_join(ohi, areas, by="iso3c")

#write_csv(ohi, here("_data/output/score_dimensions.csv"))

```

## Flowerplot Data
```{r}
ohi <- read_csv("https://raw.githubusercontent.com/OHI-Science/ohi-global/draft/yearly_results/global2023/OHI_final_formatted_scores_2023-10-02.csv")

ohi$iso3c <- countrycode(ohi$region_name, "country.name", "iso3c")

ohi <- ohi %>%
  filter(scenario == 2023) %>%
  filter(!is.na(iso3c)) %>%
  filter(iso3c %in% regions$iso3c) %>%
  select(iso3c, region_name, goal, dimension, score=value)  %>%
  filter(dimension=="score")

areas <- st_drop_geometry(select(regions, c(iso3c, are_km2))) %>%
  filter(!(iso3c %in% c("SDN/EGY", "ERI/DJI"))) %>%
  group_by(iso3c) %>%
  summarize(are_km2 = sum(are_km2))

ohi <- left_join(ohi, areas, by="iso3c")

ohi_avgs <- ohi %>%
  group_by(goal, dimension) %>%
  summarize(score = round(weighted.mean(score, are_km2, na.rm=TRUE), 0)) %>%
  mutate(iso3c = "GLO",
         region_name = "Global average",
         goal = goal,
         dimension = "score",
         score = score,
         are_km2 = NA
         )

flower_data <- rbind(ohi, ohi_avgs) %>%
  select(-are_km2)

#write_csv(flower_data, here("_data/output/flowerplot_scores.csv"))

```



## get region data
```{r}
ohi_rgns <- read_csv("https://raw.githubusercontent.com/OHI-Science/ohi-global/draft/yearly_results/global2023/OHI_final_formatted_scores_2023-10-02.csv")

ohi_rgns$iso3c <- countrycode(ohi_rgns$region_name, "country.name", "iso3c")

ohi_rgns <- ohi_rgns %>%
  filter(scenario == 2023) %>%
  select(iso3c, region_name, rgn_id=region_id) %>%
  unique()

rsga_regions <- st_read(here("_spatial/data/eez.shp")) %>%
  filter(!(iso3c %in% c("SDN/EGY", "ERI/DJI"))) %>%
  pull(iso3c) %>%
  unique()

rsga_ohi_regions <- filter(ohi_rgns, iso3c %in% rsga_regions)

#write_csv(ohi_rgns, here("_data/output/ohi_rgns.csv"))
#write_csv(rsga_ohi_regions, here("_data/output/rsga_ohi_rgns.csv"))


```